version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: alimama-postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    # volumes:
    #   - ./database/postgresql:/var/lib/pgsql/data
    networks:
      - my-network

  mongo:
    image: mongo:6
    container_name: alimama-mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    # volumes:
    #   - ./database/mongodb:/data/db
    networks:
      - my-network

volumes:
  postgres-data:
  mongo-data:

networks:
  my-network:
    driver: bridge