services:
  # PostgreSQL
  postgres:
    image: postgres:16.3
    container_name: alimama-postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - my-network

  # MongoDB
  mongo:
    image: mongo:6
    container_name: alimama-mongodb-container
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  # Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alimama-springboot-container
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - postgres
      - mongo
    networks:
      - my-network
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  # React.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: alimama-frontend-container
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:${BACKEND_PORT}/api
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - my-network

volumes:
  postgres-data:
  mongo-data:

networks:
  my-network:
    driver: bridge
